version: "3.9"
services:
  web:
    image: "jekyll/jekyll:4.2.0"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - jekyll-cache:/usr/local/bundle
    command: jekyll serve

volumes:
  jekyll-cache:
